from selenium import webdriver
from selenium.webdriver.support.select import Select
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
driver = webdriver.Chrome("C:\\Users\\BB\\Downloads\\driver\\chromedriver.exe")
driver.get("https://opensource-demo.orangehrmlive.com/")
driver.maximize_window()
driver.implicitly_wait(8)
driver.find_element_by_name("txtUsername").send_keys("Admin")
driver.find_element_by_name("txtPassword").send_keys("admin123")
driver.find_element_by_xpath("//input[@id='btnLogin']").click()
action = ActionChains(driver)
Time = driver.find_element_by_xpath("//a[@id='menu_time_viewTimeModule']")
action.move_to_element(Time)
Attendance = driver.find_element_by_xpath("//a[@id='menu_attendance_Attendance']")
action.move_to_element(Attendance)
Punch_In = driver.find_element_by_xpath("//a[@id='menu_attendance_punchIn']")
action.move_to_element(Punch_In)
action.click(Punch_In)
action.perform()
driver.find_element_by_xpath("//img[@class='ui-datepicker-trigger']").click()
year = Select(driver.find_element_by_xpath("//select[@class='ui-datepicker-year']")).select_by_value("2020")
month = Select(driver.find_element_by_xpath("//select[@class='ui-datepicker-month']")).select_by_value("9")
driver.find_element_by_xpath("//tbody/tr[4]/td[5]").click()
driver.find_element_by_xpath("//input[@id='attendance_time']").send_keys("10:30")
driver.find_element_by_xpath("//textarea[@id='attendance_note']").send_keys("punch in ")
driver.find_element_by_xpath("//input[@class='punchInbutton']").click()
print("punch in sucessfull")
driver.find_element_by_xpath("//img[@class='ui-datepicker-trigger']").click()
Year = Select(driver.find_element_by_xpath("//select[@class='ui-datepicker-year']")).select_by_value("2020")
Month = Select(driver.find_element_by_xpath("//select[@class='ui-datepicker-month']")).select_by_value("9")
driver.find_element_by_xpath("//tbody/tr[4]/td[5]").click()
driver.find_element_by_xpath("//input[@id='attendance_time']").send_keys("06:30")
driver.find_element_by_xpath("//textarea[@id='attendance_note']").send_keys("punch out ")
driver.find_element_by_xpath("//input[@class='punchOutbutton']").click()
print("punch out sucessfull")